services:
  server:
    build: .
    container_name: camera-server
    ports:
      - "8000:8000"
      - "8888:8888"
    volumes:
      - ./recordings:/app/recordings
      - ./database:/app/database
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8000', res => res.statusCode === 200 ? process.exit(0) : process.exit(1), req => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    stop_grace_period: 10s
    networks:
      - monitoring_monitoring

networks:
  monitoring_monitoring:
    external: true

    